### ISSUE TITLE
update dependabot.yml to use some milestone + time zone

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#2168]
@tomholub I also propose to update [dependabot.yml](https://github.com/FlowCrypt/flowcrypt-android/blob/master/.github/dependabot.yml) to automatically move dependabot's PRs to a predefined milestone. After that, a milestone also will include dependencies updates.

https://github.com/dependabot/feedback/issues/561
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#milestone

```
# Specify a milestone for pull requests

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Associate pull requests with milestone "4"
    milestone: 4
```

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/2161#issuecomment-1398336638_
